# Generated by Django 3.0.8 on 2020-07-11 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('player', models.CharField(max_length=45)),
                ('highscore', models.IntegerField()),
                ('record_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
